// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./layouts/BaseSide.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    MatchPage: typeof import('./views/MatchPage.vue')['default']
    MessageTab: typeof import('./components/MessageTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPage: typeof import('./views/SettingPage.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
