// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./layouts/BaseSide.vue')['default']
    ChatArea: typeof import('./components/ChatArea.vue')['default']
    ChatBox: typeof import('./components/ChatBox.vue')['default']
    ChatList: typeof import('./components/ChatList.vue')['default']
    ChatPage: typeof import('./views/ChatPage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LikedBox: typeof import('./components/LikedBox.vue')['default']
    LikedList: typeof import('./components/LikedList.vue')['default']
    LoginPage: typeof import('./views/LoginPage.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    MatchPage: typeof import('./views/MatchPage.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    RegisterPage: typeof import('./views/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPage: typeof import('./views/SettingPage.vue')['default']
    SigninForm: typeof import('./components/SigninForm.vue')['default']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
  }
}
